# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.sol'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.sol'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Hardhat
      run: npm install --save-dev hardhat
    - name: Install Hardhat Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
